# Generated by Django 4.2 on 2025-03-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zero_product',
            name='brand',
            field=models.CharField(default='', max_length=50, verbose_name='브랜드명'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='칼로리 (kcal)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='image',
            field=models.ImageField(default='products/sample.jpg', upload_to='products/', verbose_name='제품 이미지'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='원재료 세부정보'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='total_grams',
            field=models.IntegerField(default=0, verbose_name='총 용량 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='warnings',
            field=models.TextField(blank=True, verbose_name='혈당 주의 성분'),
        ),
    ]
