# Generated by Django 4.2 on 2025-03-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_zero_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zero_product',
            name='glucose_syrup',
        ),
        migrations.RemoveField(
            model_name='zero_product',
            name='maltitol',
        ),
        migrations.RemoveField(
            model_name='zero_product',
            name='maltitol_syrup',
        ),
    ]
